global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using ExcelEFCore;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using OfficeOpenXml.Attributes;
global using OfficeOpenXml.Table;
global using System.Drawing;
global using System.Reflection;
global using Microsoft.EntityFrameworkCore;
